# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
FROM node:18-alpine AS builder

# Install pnpm
RUN npm install -g pnpm

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

# Bundle app source
COPY . .

# Build the app
RUN pnpm run build

# Stage 2: Production Image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy built app from the build stage
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json

# Expose the port MCP server runs on
EXPOSE 54321

# Start the server
CMD ["node", "dist/extension.cjs"]
